apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -o k8s -f .docker-compose.yml
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: static-app
  name: static-app
  namespace: default
spec:
  ports:
    - name: "8083"
      port: 8083
      targetPort: 80
  selector:
    io.kompose.service: static-app
status:
  loadBalancer: {}
